### ISSUE TITLE
when i commented on an issue the description disappeared until refresh - happens when anything is changed on card

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#2609]

**Comment by adambuczynski** [comment]
+1

**Comment by adambuczynski** [comment]
This is really a serious issue that can cause data loss. It also happens when one person edits the size of an issue. If another person was editing the issue at the same time, the description is cleared for them as well.

**Comment by poolebu** [comment]
Hello, this is happening to me also, right after I post a comment I loose the description. It's bad, it's forcing me to go to github and use their issue editor, I like writing lots on the cards.

**Comment by songawee** [comment]
Hey @adambuczynski and @poolebu, we just pushed a fix for this issue. Sorry for the troubles and let us know if you have any other issues.

Thanks!

**Comment by adambuczynski** [comment]
Thanks @songawee . Out of curiosity, what was causing this issue?

**Comment by songawee** [comment]
@adambuczynski There was an issue with how we update cards. We weren't merging the data between the existing card and the updated card correctly. Thanks!

**Comment by seanperkins** [comment]
I am still having this happen to me. I go to Github to create issues since Waffle doesn't support pasting images from clipboard like Github does. If I move any cards in Waffle prior to refreshing, it clears out my description.
